#!/bin/sh

PY_FILES="__main__.py  other.py  translate.py"
PY_DEPS="sox googletrans google_speech"
NAME="trscli"
INSTALL_DIR="/usr/local/bin/"


clean()
{
	echo "Cleaning"
	rm $NAME".zip"
}
install()
{
	echo "Installing."
	mv $NAME $INSTALL_DIR || echo "Installation failed. Try running as root."
}
checkdep()
{
	python -c "import $1" && return 1
	echo "Error: Dependency '$1' is not present. Try pip installing it. (pip intall $1)"
	exit
}

echo "Checking dependencies"
for file in $PY_DEPS; do
	checkdep $file
done



echo "Creating binary"
zip $NAME $PY_FILES  >> /dev/null || $(echo "Zipping files failed" & exit)
echo '#!/usr/bin/env python3' > $NAME
cat $NAME".zip" >> $NAME
chmod +xr $NAME




while getopts "ci" o; do
	case "${o}" in
		c)
			clean
			;;
		i)
			install
			;;
	esac
done
